export const INDICES = [
  "NIFTY 50", "BANKNIFTY", "FINNIFTY", "SENSEX", "INDIA VIX",
  "NIFTY MIDCAP 100", "NIFTY SMALLCAP 100", "NIFTY NEXT 50",
  "NIFTY IT", "NIFTY AUTO", "NIFTY METAL", "NIFTY PHARMA", 
  "NIFTY FMCG", "NIFTY ENERGY", "NIFTY PSU BANK", "NIFTY PVT BANK",
  "NIFTY REALTY", "NIFTY MEDIA", "NIFTY INFRA", "NIFTY COMMODITIES"
];

export const NIFTY_50 = [
  "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK",
  "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BEL", "BHARTIARTL",
  "BPCL", "BRITANNIA", "CIPLA", "COALINDIA", "DIVISLAB",
  "DRREDDY", "EICHERMOT", "GRASIM", "HCLTECH", "HDFCBANK",
  "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK",
  "INDUSINDBK", "INFY", "ITC", "JSWSTEEL", "KOTAKBANK",
  "LT", "LTIM", "M&M", "MARUTI", "NESTLEIND",
  "NTPC", "ONGC", "POWERGRID", "RELIANCE", "SBILIFE",
  "SBIN", "SHRIRAMFIN", "SUNPHARMA", "TATACONSUM", "TATAMOTORS",
  "TATASTEEL", "TCS", "TECHM", "TITAN", "TRENT",
  "ULTRACEMCO", "WIPRO"
];

export const NIFTY_NEXT_50 = [
  "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "ATGL", "AMBUJACEM", 
  "BANKBARODA", "BERGEPAINT", "BHEL", "BOSCHLTD", "CANBK", "CHOLAFIN", 
  "COLPAL", "DLF", "DMART", "GAIL", "GODREJCP", "HAL", "HAVELLS", 
  "HDFCAMC", "HINDPETRO", "ICICIGI", "ICICIPRULI", "IOC", "IRCTC", 
  "JINDALSTEL", "JIOFIN", "JSWINFRA", "LICI", "LUPIN", "MARICO", 
  "MOTHERSON", "NAUKRI", "PIDILITIND", "PNB", "PFC", "PGHH", "PIIND", 
  "RECLTD", "SBICARD", "SHREECEM", "SIEMENS", "SRF", "TORNTPHARM", 
  "TVSMOTOR", "UBL", "UNITEDSPIRITS", "VEDL", "ZOMATO", "ZYDUSLIFE"
];

export const MIDCAP_SELECT = [
    "ACC", "APLAPOLLO", "ASTRAL", "AUROPHARMA", "BALKRISIND", "BHARATFORG", 
    "CUMMINSIND", "FEDERALBNK", "INDHOTEL", "MPHASIS", "MRF", "OFSS", 
    "PAGEIND", "PETRONET", "POLYCAB", "TATACOMM", "VOLTAS", "ASHOKLEY", 
    "BALRAMCHIN", "BANDHANBNK", "BANKINDIA", "BATAINDIA", "COFORGE", 
    "CONCOR", "COROMANDEL", "CROMPTON", "DALBHARAT", "DEEPAKNTR", 
    "DELTACORP", "ESCORTS", "FORTIS", "GLENMARK", "GMRINFRA", "GODREJPROP", 
    "GRANULES", "GUJGASLTD", "HAPPSTMNDS", "HINDCOPPER", "IDFCFIRSTB", 
    "IGL", "INDIGOPNTS", "IPCALAB", "JSL", "JUBLFOOD", "LALPATHLAB", 
    "LAURUSLABS", "L&TFH", "MANAPPURAM", "MFSL", "M&MFIN", "NAM-INDIA", 
    "NATIONALUM", "NAVINFLUOR", "OBEROIRLTY", "PERSISTENT", "PVRINOX", 
    "RAIN", "RAMCOCEM", "RBLBANK", "SAIL", "SUNTV", "SYNGENE", "TATACHEM", 
    "TATAPOWER", "TATAELXSI", "JKCEMENT", "KAJARIACER", "KEI"
];

export const SMALLCAP_SELECT = [
  "ALOKINDS", "AMBER", "ANGELONE", "ANURAS", "ASTERDM", "AVANTIFEED", "BASF",
  "BCG", "BEML", "BIRLACORPN", "BLS", "BLUESTARCO", "BORORENEW", "BSE", "BSOFT",
  "CAMPUS", "CAMS", "CASTROLIND", "CDSL", "CENTURYPLY", "CESC", "CHAMBLFERT",
  "CHEMPLASTS", "CHOLAHLDNG", "CIEINDIA", "CREDITACC", "CYIENT", "DATAPATTNS",
  "DCMSHRIRAM", "DEEPAKFERT", "DEVYANI", "ECLERX", "EIDPARRY", "EIHOTEL",
  "ELGIEQUIP", "ENDURANCE", "ENGINERSIN", "EPL", "EQUITASBNK", "ERIS", "EXIDEIND",
  "FSL", "GLS", "GMMPFAUDLR", "GNFC", "GODFRYPHLP", "GPPL", "GRAPHITE", "GRINDWELL",
  "GSFC", "GSPL", "HEG", "HFCL", "HIKAL", "HINDZINC", "HITACHI", "HONAUT",
  "HSCL", "HUDCO", "IEX", "IDBI", "IDFC", "IIFL", "INDDIAM", "INDIAMART",
  "INDIANB", "INDIGOREM", "INTELLECT", "IOB", "IRFC", "IRCON", "ITI", "J&KBANK",
  "JBCHEPHARM", "JINDALSAW", "JKLAKSHMI", "JKPAPER", "JKTYRE", "JYOTHYLAB",
  "KALYANKJIL", "KARURVYSYA", "KEC", "KNRCON", "KPITTECH", "KRBL", "KSB",
  "LATENTVIEW", "LAXMIMACH", "LEMONTREE", "LICHSGFIN", "LINDEINDIA", "MAHABANK",
  "MAHLIFE", "MANINFRA", "MAPMYINDIA", "MASTEK", "MAZAGONDOC", "MCX", "METROPOLIS",
  "MGL", "MMTC", "MOIL", "MRPL", "MSTCLTD", "MTARTECH", "NBCC", "NCC", "NH",
  "NHPC", "NLCINDIA", "NMDC", "NSL", "NUVAMA", "OLECTRA", "OIL", "PATANJALI",
  "PPLPHARMA", "PRAJIND", "PRESTIGE", "PRINCEPIPE", "PRISMJOHN", "QUESS",
  "RADICO", "RAILTEL", "RAJESHEXPO", "RATNAMANI", "RAYMOND", "RCF", "REDINGTON",
  "RENUKA", "RHIM", "RITES", "ROSSARI", "ROUTE", "RVNL", "SAPPHIRE", "SCI",
  "SHYAMMETL", "SJVN", "SKFINDIA", "SOBHA", "SONACOMS", "STARHEALTH", "STLTECH",
  "SUMICHEM", "SUNDARMFIN", "SUNDRMFAST", "SUNTECK", "SUPRAJIT", "SUZLON",
  "SWANENERGY", "TANLA", "TATAINVEST", "TEJASNET", "TITAGARH", "TRITURBINE",
  "TRIVENI", "UCOBANK", "UNIONBANK", "UTIAMC", "VAIBHAVGBL", "VAKRANGEE",
  "VARROC", "VGUARD", "VIPIND", "WELCORP", "WELSPUNLIV", "WESTLIFE", "WHIRLPOOL",
  "YESBANK", "ZENSARTECH"
];

export const NIFTY_100 = [...NIFTY_50, ...NIFTY_NEXT_50].sort();
export const NIFTY_200 = [...NIFTY_100, ...MIDCAP_SELECT].sort();
export const NIFTY_500 = [...NIFTY_200, ...SMALLCAP_SELECT].sort();
